[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
er_transfer = "6usNHyiitnGsAaswdKpLaE69Ax1SG162ZrhdfmPreLWQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS='--import tsx' yarn run mocha --timeout 1000000 tests/**/*.ts"
